name: CD - Despliegue de la solución con Serverless Framework
on:
  workflow_run:
    workflows: ["CI - Pruebas de Integración Continua"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Instalar dependencias
        run: npm install

      - name: configurar AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: set serverless credentials
        run: echo "SERVERLESS_ACCESS_KEY=${{ secrets.SERVERLESS_ACCESS_KEY }}" >> $GITHUB_ENV
      
      # - name: set bucket name for serverless deployment
      #   run: echo "DEPLOYMENT_BUCKET=${{ secrets.DEPLOYMENT_BUCKET }}" >> $GITHUB_ENV

      - name: Set de variables de entorno
        run: echo "ENVIRONMENT=${{ secrets.ENVIRONMENT }}" >> $GITHUB_ENV

      - name: Set de variables de entorno
        run: echo "DB_HOST=${{ secrets.DB_HOST }}" >> $GITHUB_ENV

      - name: Set de variables de entorno
        run: echo "USER_DB=${{ secrets.USER_DB }}" >> $GITHUB_ENV
      
      - name: Set de variables de entorno
        run: echo "PASSWORD=${{ secrets.PASSWORD }}" >> $GITHUB_ENV
      
      - name: Set de variables de entorno
        run: echo "DATABASE=${{ secrets.DATABASE }}" >> $GITHUB_ENV

      - name: Desplegar con Serverless Framework
        run: npx serverless deploy --stage ${{ secrets.ENVIRONMENT }} --region ${{ secrets.AWS_REGION }} --verbose